- hosts: linux
  become: yes
  tasks:
    - name: "Ensure group - piyush"
      group:
       name: piyush
       state: present

    - name: "Add the user - piyush"
      user:
       name: piyush
       comment: piyush
       group: piyush
       update_password: on_create
